name: Compile Swagger Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -DskipTests -B package --file pom.xml
    - name: deploy
      
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mkdir -p ~/.m2
        echo "<settings><servers><server><id>github</id><username>OWNER</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
        mvn -DskipTests deploy --file=modules/swagger-annotations/pom.xml
        mvn -DskipTests deploy --file=modules/swagger-core/pom.xml
        mvn -DskipTests deploy --file=modules/swagger-integration/pom.xml
        mvn -DskipTests deploy --file=modules/swagger-jaxrs2/pom.xml
        mvn -DskipTests deploy --file=modules/swagger-jaxrs2-servlet-initializer/pom.xml
        mvn -DskipTests deploy --file=modules/swagger-maven-plugin/pom.xml
        mvn -DskipTests deploy --file=modules/swagger-models/pom.xml
